import type { SeedSpecies } from "./types";

export const SPECIES_SEED: SeedSpecies[] = [
  // Freshwater Europe
  { common_name: "Brown Trout", scientific_name: "Salmo trutta", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Bachforelle", "Truite fario", "Sea Trout"] },
  { common_name: "Rainbow Trout", scientific_name: "Oncorhynchus mykiss", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe", "Freshwater North America"], aliases: ["Steelhead", "Regenbogenforelle"] },
  { common_name: "Atlantic Salmon", scientific_name: "Salmo salar", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe", "North Atlantic"], aliases: ["Salmon", "Saumon", "Lachs"] },
  { common_name: "Brook Trout", scientific_name: "Salvelinus fontinalis", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe", "Freshwater North America"], aliases: ["Brookie", "Speckled Trout", "Bachsaibling"] },
  { common_name: "Arctic Char", scientific_name: "Salvelinus alpinus", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Char", "Saibling"] },
  { common_name: "Grayling", scientific_name: "Thymallus thymallus", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Äsche", "Lady of the Stream"] },
  { common_name: "Huchen", scientific_name: "Hucho hucho", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Danube Salmon", "Huch"] },
  { common_name: "Common Whitefish", scientific_name: "Coregonus lavaretus", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Lavaret", "Felchen", "Renke"] },
  { common_name: "Vendace", scientific_name: "Coregonus albula", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["European Cisco", "Kleine Maräne"] },
  { common_name: "Northern Pike", scientific_name: "Esox lucius", family: "Esocidae", water_type: "Freshwater", regions: ["Freshwater Europe", "Freshwater North America"], aliases: ["Pike", "Jackfish", "Snake", "Hecht", "Brochet"] },
  { common_name: "Zander", scientific_name: "Sander lucioperca", family: "Percidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Pike-perch", "Sandre"] },
  { common_name: "European Perch", scientific_name: "Perca fluviatilis", family: "Percidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Perch", "Redfin", "Flussbarsch", "Perche"] },
  { common_name: "Ruffe", scientific_name: "Gymnocephalus cernua", family: "Percidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Pope", "Kaulbarsch"] },
  { common_name: "Burbot", scientific_name: "Lota lota", family: "Lotidae", water_type: "Freshwater", regions: ["Freshwater Europe", "Freshwater North America"], aliases: ["Quappe", "Lotte", "Freshwater Ling"] },
  { common_name: "Common Carp", scientific_name: "Cyprinus carpio", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe", "Levant / Eastern Med"], aliases: ["King Carp", "Karpfen", "קרפיון"] },
  { common_name: "Mirror Carp", scientific_name: "Cyprinus carpio carpio", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Mirror", "Spiegelkarpfen"] },
  { common_name: "Crucian Carp", scientific_name: "Carassius carassius", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Karausche"] },
  { common_name: "Tench", scientific_name: "Tinca tinca", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Doctor Fish", "Schleie", "Tanche"] },
  { common_name: "Common Bream", scientific_name: "Abramis brama", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Bronze Bream", "Brachsen", "Brème"] },
  { common_name: "Roach", scientific_name: "Rutilus rutilus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Plötze", "Rotauge", "Gardon"] },
  { common_name: "Rudd", scientific_name: "Scardinius erythrophthalmus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Rotfeder"] },
  { common_name: "Chub", scientific_name: "Squalius cephalus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Aitel", "Döbel", "Chevesne"] },
  { common_name: "Asp", scientific_name: "Leuciscus aspius", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Rapfen", "Aspe"] },
  { common_name: "Ide", scientific_name: "Leuciscus idus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Orfe", "Aland", "Golden Orfe"] },
  { common_name: "Dace", scientific_name: "Leuciscus leuciscus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Hasel", "Vandoise"] },
  { common_name: "Barbel", scientific_name: "Barbus barbus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Barbe", "Barbeau"] },
  { common_name: "Bleak", scientific_name: "Alburnus alburnus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Laube", "Ablette"] },
  { common_name: "Gudgeon", scientific_name: "Gobio gobio", family: "Cyprinidae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Gründling", "Goujon"] },
  { common_name: "European Eel", scientific_name: "Anguilla anguilla", family: "Anguillidae", water_type: "Freshwater", regions: ["Freshwater Europe", "Brackish"], aliases: ["Eel", "Aal", "Anguille"] },
  { common_name: "Wels Catfish", scientific_name: "Silurus glanis", family: "Siluridae", water_type: "Freshwater", regions: ["Freshwater Europe"], aliases: ["Wels", "Sheatfish", "Waller", "Silure"] },

  // Freshwater North America
  { common_name: "Largemouth Bass", scientific_name: "Micropterus salmoides", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Bucketmouth", "Hawg", "Bigmouth", "Black Bass", "LMB"] },
  { common_name: "Smallmouth Bass", scientific_name: "Micropterus dolomieu", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Smallie", "Bronzeback", "SMB"] },
  { common_name: "Spotted Bass", scientific_name: "Micropterus punctulatus", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Spotty", "Kentucky Bass"] },
  { common_name: "Bluegill", scientific_name: "Lepomis macrochirus", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Bream", "Sunny", "Sun Perch", "Brim"] },
  { common_name: "Redear Sunfish", scientific_name: "Lepomis microlophus", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Shellcracker", "Stumpknocker"] },
  { common_name: "Pumpkinseed", scientific_name: "Lepomis gibbosus", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Sunfish", "Common Sunfish"] },
  { common_name: "Black Crappie", scientific_name: "Pomoxis nigromaculatus", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Crappie", "Speckled Perch", "Calico Bass"] },
  { common_name: "White Crappie", scientific_name: "Pomoxis annularis", family: "Centrarchidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Crappie", "Sac-a-lait"] },
  { common_name: "Walleye", scientific_name: "Sander vitreus", family: "Percidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Pickerel", "Yellow Pike"] },
  { common_name: "Yellow Perch", scientific_name: "Perca flavescens", family: "Percidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Perch", "Lake Perch"] },
  { common_name: "Muskellunge", scientific_name: "Esox masquinongy", family: "Esocidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Musky", "Muskie", "Lunge"] },
  { common_name: "Chain Pickerel", scientific_name: "Esox niger", family: "Esocidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Chainsides", "Jack"] },
  { common_name: "Lake Trout", scientific_name: "Salvelinus namaycush", family: "Salmonidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Mackinaw", "Togue", "Laker"] },
  { common_name: "Channel Catfish", scientific_name: "Ictalurus punctatus", family: "Ictaluridae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Channel Cat", "Spotted Cat"] },
  { common_name: "Blue Catfish", scientific_name: "Ictalurus furcatus", family: "Ictaluridae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Blue Cat"] },
  { common_name: "Flathead Catfish", scientific_name: "Pylodictis olivaris", family: "Ictaluridae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Mudcat", "Yellow Cat", "Shovelhead"] },
  { common_name: "Bowfin", scientific_name: "Amia calva", family: "Amiidae", water_type: "Freshwater", regions: ["Freshwater North America"], aliases: ["Dogfish", "Mudfish", "Grinnel"] },
  { common_name: "Northern Snakehead", scientific_name: "Channa argus", family: "Channidae", water_type: "Freshwater", regions: ["Freshwater North America", "Asia / Indo-Pacific"], aliases: ["Snakehead", "Frankenfish"] },

  // Saltwater Mediterranean & North Atlantic (European)
  { common_name: "European Seabass", scientific_name: "Dicentrarchus labrax", family: "Moronidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic", "Levant / Eastern Med"], aliases: ["Branzino", "Loup de mer", "Spigola", "Sea Bass", "Lubina", "לברק"] },
  { common_name: "Gilthead Seabream", scientific_name: "Sparus aurata", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean", "Levant / Eastern Med"], aliases: ["Dorade", "Orata", "Dorada", "Dorade royale", "דניס"] },
  { common_name: "Common Dentex", scientific_name: "Dentex dentex", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Dentex", "Dentice", "Denté"] },
  { common_name: "Common Pandora", scientific_name: "Pagellus erythrinus", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Pandora", "Pagello", "Pageot"] },
  { common_name: "White Seabream", scientific_name: "Diplodus sargus", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Sargo", "Sar commun", "Sargo blanco"] },
  { common_name: "Two-banded Seabream", scientific_name: "Diplodus vulgaris", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Common Two-banded Sea Bream", "Sargo"] },
  { common_name: "Black Seabream", scientific_name: "Spondyliosoma cantharus", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Cantaro", "Tanuda", "Old Wife"] },
  { common_name: "Bogue", scientific_name: "Boops boops", family: "Sparidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Boops", "Bopa", "Boga"] },
  { common_name: "Red Mullet", scientific_name: "Mullus surmuletus", family: "Mullidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Surmullet", "Rouget", "Triglia"] },
  { common_name: "Sand Smelt", scientific_name: "Atherina hepsetus", family: "Atherinidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Atherina", "Latterino", "Joël"] },
  { common_name: "Garfish", scientific_name: "Belone belone", family: "Belonidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Gar", "Hornhecht", "Orphie"] },
  { common_name: "Conger Eel", scientific_name: "Conger conger", family: "Congridae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Conger", "Grongo", "Congrio"] },
  { common_name: "Mediterranean Scorpionfish", scientific_name: "Scorpaena scrofa", family: "Scorpaenidae", water_type: "Saltwater", regions: ["Mediterranean"], aliases: ["Red Scorpionfish", "Rascasse", "Scorfano"] },
  { common_name: "John Dory", scientific_name: "Zeus faber", family: "Zeidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["St. Peter's Fish", "Pesce San Pietro", "Pez de San Pedro", "Saint-Pierre"] },
  { common_name: "Common Sole", scientific_name: "Solea solea", family: "Soleidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Dover Sole", "Sogliola", "Sole commune"] },
  { common_name: "European Hake", scientific_name: "Merluccius merluccius", family: "Merlucciidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Hake", "Merlu", "Merluza"] },
  { common_name: "Meagre", scientific_name: "Argyrosomus regius", family: "Sciaenidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Corvina", "Maigre", "Ombrina"] },
  { common_name: "Grey Mullet", scientific_name: "Mugil cephalus", family: "Mugilidae", water_type: "Brackish", regions: ["Mediterranean", "North Atlantic", "Levant / Eastern Med"], aliases: ["Flathead Mullet", "Cefalo", "Mulet", "בורי"] },
  { common_name: "European Anchovy", scientific_name: "Engraulis encrasicolus", family: "Engraulidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Anchovy", "Anchois", "Acciuga"] },
  { common_name: "Bluefin Tuna", scientific_name: "Thunnus thynnus", family: "Scombridae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Tuna", "Atún", "Toro", "Thon rouge"] },
  { common_name: "Atlantic Bonito", scientific_name: "Sarda sarda", family: "Scombridae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Bonito", "Palamida", "Pelamide"] },
  { common_name: "Greater Amberjack", scientific_name: "Seriola dumerili", family: "Carangidae", water_type: "Saltwater", regions: ["Mediterranean", "Tropical / Indo-Pacific"], aliases: ["Amberjack", "AJ", "Reef Donkey", "Ricciola"] },
  { common_name: "Mahi-mahi", scientific_name: "Coryphaena hippurus", family: "Coryphaenidae", water_type: "Saltwater", regions: ["Mediterranean", "Tropical / Indo-Pacific"], aliases: ["Dorado", "Dolphinfish", "Coryphène", "Lampuga"] },
  { common_name: "Swordfish", scientific_name: "Xiphias gladius", family: "Xiphiidae", water_type: "Saltwater", regions: ["Mediterranean", "North Atlantic"], aliases: ["Broadbill", "Pez Espada", "Espadon", "Pesce spada"] },
  { common_name: "Atlantic Cod", scientific_name: "Gadus morhua", family: "Gadidae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Cod", "Codfish", "Kabeljau", "Cabillaud"] },
  { common_name: "Pollock", scientific_name: "Pollachius pollachius", family: "Gadidae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Saithe", "Coley", "Lieu jaune"] },
  { common_name: "Haddock", scientific_name: "Melanogrammus aeglefinus", family: "Gadidae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Schellfisch", "Églefin"] },
  { common_name: "Atlantic Mackerel", scientific_name: "Scomber scombrus", family: "Scombridae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Mackerel", "Maquereau", "Makrele", "Sgombro"] },
  { common_name: "Atlantic Halibut", scientific_name: "Hippoglossus hippoglossus", family: "Pleuronectidae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Halibut", "Heilbutt", "Flétan"] },
  { common_name: "European Plaice", scientific_name: "Pleuronectes platessa", family: "Pleuronectidae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Plaice", "Scholle", "Plie"] },
  { common_name: "Striped Bass", scientific_name: "Morone saxatilis", family: "Moronidae", water_type: "Saltwater", regions: ["North Atlantic"], aliases: ["Striper", "Rockfish", "Linesider", "Stripey"] },

  // Saltwater Tropical / Indo-Pacific
  { common_name: "Sailfish", scientific_name: "Istiophorus platypterus", family: "Istiophoridae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["Sail", "Spindlebeak"] },
  { common_name: "Blue Marlin", scientific_name: "Makaira nigricans", family: "Istiophoridae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["Marlin"] },
  { common_name: "Wahoo", scientific_name: "Acanthocybium solandri", family: "Scombridae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["Ono", "Hoo"] },
  { common_name: "Giant Trevally", scientific_name: "Caranx ignobilis", family: "Carangidae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["GT", "Ulua", "Trevally"] },
  { common_name: "Yellowfin Tuna", scientific_name: "Thunnus albacares", family: "Scombridae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific", "North Atlantic"], aliases: ["Ahi", "Yellowfin", "Thon jaune"] },
  { common_name: "Bonefish", scientific_name: "Albula vulpes", family: "Albulidae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["Gray Ghost", "Macabi"] },
  { common_name: "Indo-Pacific Permit", scientific_name: "Trachinotus blochii", family: "Carangidae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["Snub-nose Pompano", "Permit"] },
  { common_name: "Queenfish", scientific_name: "Scomberoides commersonnianus", family: "Carangidae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific"], aliases: ["Talang Queenfish", "Largemouth Queenfish"] },
  { common_name: "Barramundi", scientific_name: "Lates calcarifer", family: "Latidae", water_type: "Brackish", regions: ["Tropical / Indo-Pacific", "Asia / Indo-Pacific"], aliases: ["Asian Sea Bass", "Giant Perch", "Barra"] },
  { common_name: "Fourfinger Threadfin", scientific_name: "Eleutheronema tetradactylum", family: "Polynemidae", water_type: "Saltwater", regions: ["Tropical / Indo-Pacific", "Asia / Indo-Pacific"], aliases: ["Threadfin", "Threadfin Salmon"] },
  { common_name: "Striped Snakehead", scientific_name: "Channa striata", family: "Channidae", water_type: "Freshwater", regions: ["Asia / Indo-Pacific"], aliases: ["Snakehead", "Murrel", "Common Snakehead"] },
  { common_name: "Indian Mahseer", scientific_name: "Tor tor", family: "Cyprinidae", water_type: "Freshwater", regions: ["Asia / Indo-Pacific"], aliases: ["Mahseer", "Tor"] },
  { common_name: "Golden Mahseer", scientific_name: "Tor putitora", family: "Cyprinidae", water_type: "Freshwater", regions: ["Asia / Indo-Pacific"], aliases: ["Himalayan Mahseer", "Putitor Mahseer"] },

  // Brackish & coastal North America (warm-water)
  { common_name: "Red Drum", scientific_name: "Sciaenops ocellatus", family: "Sciaenidae", water_type: "Saltwater", regions: ["Freshwater North America"], aliases: ["Redfish", "Channel Bass", "Spottail Bass"] },
  { common_name: "Black Drum", scientific_name: "Pogonias cromis", family: "Sciaenidae", water_type: "Saltwater", regions: ["Freshwater North America"], aliases: ["Drum", "Drumfish"] },
  { common_name: "Spotted Seatrout", scientific_name: "Cynoscion nebulosus", family: "Sciaenidae", water_type: "Saltwater", regions: ["Freshwater North America"], aliases: ["Speckled Trout", "Spec", "Speck"] },
  { common_name: "Tarpon", scientific_name: "Megalops atlanticus", family: "Megalopidae", water_type: "Saltwater", regions: ["Freshwater North America", "Tropical / Indo-Pacific"], aliases: ["Silver King", "Sabalo"] },
  { common_name: "Common Snook", scientific_name: "Centropomus undecimalis", family: "Centropomidae", water_type: "Brackish", regions: ["Tropical / Indo-Pacific", "Freshwater North America"], aliases: ["Snook", "Robalo", "Linesider"] },
  { common_name: "King Mackerel", scientific_name: "Scomberomorus cavalla", family: "Scombridae", water_type: "Saltwater", regions: ["Freshwater North America", "Tropical / Indo-Pacific"], aliases: ["Kingfish", "King"] },
  { common_name: "Spanish Mackerel", scientific_name: "Scomberomorus maculatus", family: "Scombridae", water_type: "Saltwater", regions: ["Freshwater North America"], aliases: ["Spanish"] },
  { common_name: "Cobia", scientific_name: "Rachycentron canadum", family: "Rachycentridae", water_type: "Saltwater", regions: ["Freshwater North America", "Tropical / Indo-Pacific"], aliases: ["Lemonfish", "Ling", "Cobio"] },
  { common_name: "Sheepshead", scientific_name: "Archosargus probatocephalus", family: "Sparidae", water_type: "Saltwater", regions: ["Freshwater North America"], aliases: ["Convict Fish", "Sheepie"] },
  { common_name: "Mangrove Snapper", scientific_name: "Lutjanus griseus", family: "Lutjanidae", water_type: "Saltwater", regions: ["Freshwater North America", "Tropical / Indo-Pacific"], aliases: ["Gray Snapper", "Mango Snapper"] },
  { common_name: "Red Snapper", scientific_name: "Lutjanus campechanus", family: "Lutjanidae", water_type: "Saltwater", regions: ["Freshwater North America"], aliases: ["Snapper", "Sow Snapper"] },
  { common_name: "European Flounder", scientific_name: "Platichthys flesus", family: "Pleuronectidae", water_type: "Brackish", regions: ["North Atlantic", "Freshwater Europe"], aliases: ["Flounder", "Flunder", "Flet"] },

  // Levant / Eastern Med (Israel & neighbors)
  { common_name: "Mango Tilapia", scientific_name: "Sarotherodon galilaeus", family: "Cichlidae", water_type: "Freshwater", regions: ["Levant / Eastern Med", "Africa"], aliases: ["Galilee St. Peter's Fish", "Amnoun", "אמנון הגליל"] },
  { common_name: "Nile Tilapia", scientific_name: "Oreochromis niloticus", family: "Cichlidae", water_type: "Freshwater", regions: ["Levant / Eastern Med", "Africa"], aliases: ["Tilapia", "Boulti", "מושט הנילוס"] },
  { common_name: "Blue Tilapia", scientific_name: "Oreochromis aureus", family: "Cichlidae", water_type: "Freshwater", regions: ["Levant / Eastern Med", "Africa"], aliases: ["Tilapia", "Aureus"] },
  { common_name: "Yarmuk Barbel", scientific_name: "Luciobarbus longiceps", family: "Cyprinidae", water_type: "Freshwater", regions: ["Levant / Eastern Med"], aliases: ["Long-snouted Barbel"] },
  { common_name: "Lavnun", scientific_name: "Acanthobrama lissneri", family: "Cyprinidae", water_type: "Freshwater", regions: ["Levant / Eastern Med"], aliases: ["Jordan Bream", "לבנון"] },
  { common_name: "African Sharptooth Catfish", scientific_name: "Clarias gariepinus", family: "Clariidae", water_type: "Freshwater", regions: ["Levant / Eastern Med", "Africa"], aliases: ["Walking Catfish", "Sharptooth", "שפמנון מצוי"] },

  // South America
  { common_name: "Peacock Bass", scientific_name: "Cichla temensis", family: "Cichlidae", water_type: "Freshwater", regions: ["South America"], aliases: ["Tucunaré", "Pavón", "Speckled Pavon"] },
  { common_name: "Payara", scientific_name: "Hydrolycus scomberoides", family: "Cynodontidae", water_type: "Freshwater", regions: ["South America"], aliases: ["Vampire Fish", "Saber-tooth Tetra"] },
  { common_name: "Golden Dorado", scientific_name: "Salminus brasiliensis", family: "Bryconidae", water_type: "Freshwater", regions: ["South America"], aliases: ["River Tiger", "Dorado"] },
  { common_name: "Arapaima", scientific_name: "Arapaima gigas", family: "Arapaimidae", water_type: "Freshwater", regions: ["South America"], aliases: ["Pirarucu", "Paiche"] },
  { common_name: "Red-bellied Piranha", scientific_name: "Pygocentrus nattereri", family: "Serrasalmidae", water_type: "Freshwater", regions: ["South America"], aliases: ["Piranha", "Red Piranha"] },
  { common_name: "Tambaqui", scientific_name: "Colossoma macropomum", family: "Serrasalmidae", water_type: "Freshwater", regions: ["South America"], aliases: ["Black Pacu", "Cachama"] },
  { common_name: "Surubí", scientific_name: "Pseudoplatystoma corruscans", family: "Pimelodidae", water_type: "Freshwater", regions: ["South America"], aliases: ["Spotted Catfish", "Pintado"] },

  // Africa
  { common_name: "Nile Perch", scientific_name: "Lates niloticus", family: "Latidae", water_type: "Freshwater", regions: ["Africa"], aliases: ["Mbuta", "Capitaine"] },
  { common_name: "Tigerfish", scientific_name: "Hydrocynus vittatus", family: "Alestidae", water_type: "Freshwater", regions: ["Africa"], aliases: ["African Tiger"] },
  { common_name: "Goliath Tigerfish", scientific_name: "Hydrocynus goliath", family: "Alestidae", water_type: "Freshwater", regions: ["Africa"], aliases: ["Mbenga", "Goliath"] },
  { common_name: "Smallmouth Yellowfish", scientific_name: "Labeobarbus aeneus", family: "Cyprinidae", water_type: "Freshwater", regions: ["Africa"], aliases: ["Yellowfish"] },
  { common_name: "Vundu", scientific_name: "Heterobranchus longifilis", family: "Clariidae", water_type: "Freshwater", regions: ["Africa"], aliases: ["Vundu Catfish"] },
];
